/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.1.1-jre")
    // Add hibernate core
    implementation("org.hibernate.orm:hibernate-core:6.4.0.Final")
    implementation("jakarta.transaction:jakarta.transaction-api")
    implementation("com.h2database:h2:1.4.200")
    //jdbc
    implementation("org.postgresql:postgresql:42.2.19")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("hbd.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "hbd.App"
    }
}

tasks.getByName("run", JavaExec::class) {
    standardInput = System.`in`
    standardOutput = System.`out`
    isIgnoreExitValue = true
    environment("org.gradle.console", "plain")
    environment("org.gradle.q", "")
}
